package br.com.jborda.asterisk;

// Generated by DB Importer ->
// DB Importer free version - not for commercial use.
@javax.persistence.Embeddable
public class ExtensionsId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@javax.persistence.Column(name = "context", length = 20, nullable = false)
	private String context;

	public void setContext(String context) {
		this.context = context;
	}

	public String getContext() {
		return context;
	}

	@javax.persistence.Column(name = "exten", length = 20, nullable = false)
	private String exten;

	public void setExten(String exten) {
		this.exten = exten;
	}

	public String getExten() {
		return exten;
	}

	@javax.persistence.Column(name = "priority", length = 3, nullable = false)
	private short priority;

	public void setPriority(short priority) {
		this.priority = priority;
	}

	public short getPriority() {
		return priority;
	}

	public int hashCode() {
		return (context != null ? context.hashCode() : 0) + 17
				* (exten != null ? exten.hashCode() : 0) + 17 * priority;
	}

	public boolean equals(Object obj) {
		if (obj == this)
			return true;
		if (!(obj instanceof ExtensionsId))
			return false;
		ExtensionsId other = (ExtensionsId) obj;
		return (this.context != null ? this.context.equals(other.context)
				: other.context == null)
				&& (this.exten != null ? this.exten.equals(other.exten)
						: other.exten == null)
				&& this.priority == other.priority;
	}
	// <- Generated by DB Importer
}