package br.com.jborda.asterisk;

// Generated by DB Importer ->
// DB Importer free version - not for commercial use.
@javax.persistence.Entity
@javax.persistence.Table(name = "extensions")
public class Extensions {
	
	@javax.persistence.EmbeddedId
	private ExtensionsId extensionsId;

	public void setId(ExtensionsId extensionsId) {
		this.extensionsId = extensionsId;
	}

	public ExtensionsId getextensionsId() {
		return extensionsId;
	}

	@javax.persistence.Column(name = "app", length = 20, nullable = false)
	private String app = "";

	public void setApp(String app) {
		this.app = app;
	}

	public String getApp() {
		return app;
	}

	@javax.persistence.Column(name = "appdata", length = 128, nullable = false)
	private String appdata = "";

	public void setAppdata(String appdata) {
		this.appdata = appdata;
	}

	public String getAppdata() {
		return appdata;
	}

	@javax.persistence.Column(name = "id", length = 10, nullable = false)
	private int id;

	public void setId(int id) {
		this.id = id;
	}

	public int getId() {
		return id;
	}
	// <- Generated by DB Importer
}