package br.com.jborda.asterisk;

// Generated by DB Importer ->
// DB Importer free version - not for commercial use.
@javax.persistence.Entity
@javax.persistence.Table(name="queues")
public class Queues {
	
  @javax.persistence.Id
  @javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO)
  @javax.persistence.Column(name="name",length=128,nullable=false)
  private String name;

  public void setName(String name) {
    this.name = name;
  }

  public String getName() {
    return name;
  }

  @javax.persistence.Column(name="announce",length=128)
  private String announce;

  public void setAnnounce(String announce) {
    this.announce = announce;
  }

  public String getAnnounce() {
    return announce;
  }

  @javax.persistence.Column(name="announce_frequency",length=10)
  private Integer announceFrequency;

  public void setAnnounceFrequency(Integer announceFrequency) {
    this.announceFrequency = announceFrequency;
  }

  public Integer getAnnounceFrequency() {
    return announceFrequency;
  }

  @javax.persistence.Column(name="announce_holdtime",length=128)
  private String announceHoldtime;

  public void setAnnounceHoldtime(String announceHoldtime) {
    this.announceHoldtime = announceHoldtime;
  }

  public String getAnnounceHoldtime() {
    return announceHoldtime;
  }

  @javax.persistence.Column(name="announce_round_seconds",length=10)
  private Integer announceRoundSeconds;

  public void setAnnounceRoundSeconds(Integer announceRoundSeconds) {
    this.announceRoundSeconds = announceRoundSeconds;
  }

  public Integer getAnnounceRoundSeconds() {
    return announceRoundSeconds;
  }

  @javax.persistence.Column(name="context",length=128)
  private String context;

  public void setContext(String context) {
    this.context = context;
  }

  public String getContext() {
    return context;
  }

  @javax.persistence.Column(name="eventmemberstatus",length=4)
  private String eventmemberstatus;

  public void setEventmemberstatus(String eventmemberstatus) {
    this.eventmemberstatus = eventmemberstatus;
  }

  public String getEventmemberstatus() {
    return eventmemberstatus;
  }

  @javax.persistence.Column(name="eventwhencalled",length=4)
  private String eventwhencalled;

  public void setEventwhencalled(String eventwhencalled) {
    this.eventwhencalled = eventwhencalled;
  }

  public String getEventwhencalled() {
    return eventwhencalled;
  }

  @javax.persistence.Column(name="joinempty",length=128)
  private String joinempty;

  public void setJoinempty(String joinempty) {
    this.joinempty = joinempty;
  }

  public String getJoinempty() {
    return joinempty;
  }

  @javax.persistence.Column(name="leavewhenempty",length=128)
  private String leavewhenempty;

  public void setLeavewhenempty(String leavewhenempty) {
    this.leavewhenempty = leavewhenempty;
  }

  public String getLeavewhenempty() {
    return leavewhenempty;
  }

  @javax.persistence.Column(name="maxlen",length=10)
  private Integer maxlen;

  public void setMaxlen(Integer maxlen) {
    this.maxlen = maxlen;
  }

  public Integer getMaxlen() {
    return maxlen;
  }

  @javax.persistence.Column(name="memberdelay",length=10)
  private Integer memberdelay;

  public void setMemberdelay(Integer memberdelay) {
    this.memberdelay = memberdelay;
  }

  public Integer getMemberdelay() {
    return memberdelay;
  }

  @javax.persistence.Column(name="monitor_format",length=128)
  private String monitorFormat;

  public void setMonitorFormat(String monitorFormat) {
    this.monitorFormat = monitorFormat;
  }

  public String getMonitorFormat() {
    return monitorFormat;
  }

  @javax.persistence.Column(name="monitor_type",length=50,nullable=false)
  private String monitorType = "";

  public void setMonitorType(String monitorType) {
    this.monitorType = monitorType;
  }

  public String getMonitorType() {
    return monitorType;
  }

  @javax.persistence.Column(name="musiconhold",length=128)
  private String musiconhold;

  public void setMusiconhold(String musiconhold) {
    this.musiconhold = musiconhold;
  }

  public String getMusiconhold() {
    return musiconhold;
  }

  @javax.persistence.Column(name="periodic_announce",length=50)
  private String periodicAnnounce;

  public void setPeriodicAnnounce(String periodicAnnounce) {
    this.periodicAnnounce = periodicAnnounce;
  }

  public String getPeriodicAnnounce() {
    return periodicAnnounce;
  }

  @javax.persistence.Column(name="periodic_announce_frequency",length=10)
  private Integer periodicAnnounceFrequency;

  public void setPeriodicAnnounceFrequency(Integer periodicAnnounceFrequency) {
    this.periodicAnnounceFrequency = periodicAnnounceFrequency;
  }

  public Integer getPeriodicAnnounceFrequency() {
    return periodicAnnounceFrequency;
  }

  @javax.persistence.Column(name="queue_callswaiting",length=128)
  private String queueCallswaiting;

  public void setQueueCallswaiting(String queueCallswaiting) {
    this.queueCallswaiting = queueCallswaiting;
  }

  public String getQueueCallswaiting() {
    return queueCallswaiting;
  }

  @javax.persistence.Column(name="queue_holdtime",length=128)
  private String queueHoldtime;

  public void setQueueHoldtime(String queueHoldtime) {
    this.queueHoldtime = queueHoldtime;
  }

  public String getQueueHoldtime() {
    return queueHoldtime;
  }

  @javax.persistence.Column(name="queue_lessthan",length=128)
  private String queueLessthan;

  public void setQueueLessthan(String queueLessthan) {
    this.queueLessthan = queueLessthan;
  }

  public String getQueueLessthan() {
    return queueLessthan;
  }

  @javax.persistence.Column(name="queue_minutes",length=128)
  private String queueMinutes;

  public void setQueueMinutes(String queueMinutes) {
    this.queueMinutes = queueMinutes;
  }

  public String getQueueMinutes() {
    return queueMinutes;
  }

  @javax.persistence.Column(name="queue_reporthold",length=128)
  private String queueReporthold;

  public void setQueueReporthold(String queueReporthold) {
    this.queueReporthold = queueReporthold;
  }

  public String getQueueReporthold() {
    return queueReporthold;
  }

  @javax.persistence.Column(name="queue_seconds",length=128)
  private String queueSeconds;

  public void setQueueSeconds(String queueSeconds) {
    this.queueSeconds = queueSeconds;
  }

  public String getQueueSeconds() {
    return queueSeconds;
  }

  @javax.persistence.Column(name="queue_thankyou",length=128)
  private String queueThankyou;

  public void setQueueThankyou(String queueThankyou) {
    this.queueThankyou = queueThankyou;
  }

  public String getQueueThankyou() {
    return queueThankyou;
  }

  @javax.persistence.Column(name="queue_thereare",length=128)
  private String queueThereare;

  public void setQueueThereare(String queueThereare) {
    this.queueThereare = queueThereare;
  }

  public String getQueueThereare() {
    return queueThereare;
  }

  @javax.persistence.Column(name="queue_youarenext",length=128)
  private String queueYouarenext;

  public void setQueueYouarenext(String queueYouarenext) {
    this.queueYouarenext = queueYouarenext;
  }

  public String getQueueYouarenext() {
    return queueYouarenext;
  }

  @javax.persistence.Column(name="reportholdtime")
  private Boolean reportholdtime;

  public void setReportholdtime(Boolean reportholdtime) {
    this.reportholdtime = reportholdtime;
  }

  public Boolean getReportholdtime() {
    return reportholdtime;
  }

  @javax.persistence.Column(name="retry",length=10)
  private Integer retry;

  public void setRetry(Integer retry) {
    this.retry = retry;
  }

  public Integer getRetry() {
    return retry;
  }

  @javax.persistence.Column(name="ringinuse")
  private Boolean ringinuse;

  public void setRinginuse(Boolean ringinuse) {
    this.ringinuse = ringinuse;
  }

  public Boolean getRinginuse() {
    return ringinuse;
  }

  @javax.persistence.Column(name="servicelevel",length=10)
  private Integer servicelevel;

  public void setServicelevel(Integer servicelevel) {
    this.servicelevel = servicelevel;
  }

  public Integer getServicelevel() {
    return servicelevel;
  }

  @javax.persistence.Column(name="strategy",length=128)
  private String strategy;

  public void setStrategy(String strategy) {
    this.strategy = strategy;
  }

  public String getStrategy() {
    return strategy;
  }

  @javax.persistence.Column(name="timeout",length=10)
  private Integer timeout;

  public void setTimeout(Integer timeout) {
    this.timeout = timeout;
  }

  public Integer getTimeout() {
    return timeout;
  }

  @javax.persistence.Column(name="timeoutrestart")
  private Boolean timeoutrestart;

  public void setTimeoutrestart(Boolean timeoutrestart) {
    this.timeoutrestart = timeoutrestart;
  }

  public Boolean getTimeoutrestart() {
    return timeoutrestart;
  }

  @javax.persistence.Column(name="weight",length=10)
  private Integer weight;

  public void setWeight(Integer weight) {
    this.weight = weight;
  }

  public Integer getWeight() {
    return weight;
  }

  @javax.persistence.Column(name="wrapuptime",length=10)
  private Integer wrapuptime;

  public void setWrapuptime(Integer wrapuptime) {
    this.wrapuptime = wrapuptime;
  }

  public Integer getWrapuptime() {
    return wrapuptime;
  }
// <- Generated by DB Importer
}