package br.com.jborda.asterisk;

// Generated by DB Importer ->
// DB Importer free version - not for commercial use.
@javax.persistence.Entity
@javax.persistence.Table(name="queue_members", uniqueConstraints={@javax.persistence.UniqueConstraint(columnNames={"queue_name", "interface"})})
public class QueueMembers {
  @javax.persistence.Id
  @javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO)
  @javax.persistence.Column(name="uniqueid",length=10,nullable=false)
  private int uniqueid;

  public void setUniqueid(int uniqueid) {
    this.uniqueid = uniqueid;
  }

  public int getUniqueid() {
    return uniqueid;
  }

  @javax.persistence.Column(name="interface",length=128)
  private String iface;

  public void setIface(String iface) {
    this.iface = iface;
  }

  public String getIface() {
    return iface;
  }

  @javax.persistence.Column(name="membername",length=40)
  private String membername;

  public void setMembername(String membername) {
    this.membername = membername;
  }

  public String getMembername() {
    return membername;
  }

  @javax.persistence.Column(name="paused")
  private Boolean paused;

  public void setPaused(Boolean paused) {
    this.paused = paused;
  }

  public Boolean getPaused() {
    return paused;
  }

  @javax.persistence.Column(name="penalty",length=10)
  private Integer penalty;

  public void setPenalty(Integer penalty) {
    this.penalty = penalty;
  }

  public Integer getPenalty() {
    return penalty;
  }

  @javax.persistence.Column(name="queue_name",length=128)
  private String queueName;

  public void setQueueName(String queueName) {
    this.queueName = queueName;
  }

  public String getQueueName() {
    return queueName;
  }
// <- Generated by DB Importer
}