package br.com.jborda.asterisk;

// Generated by DB Importer ->
// DB Importer free version - not for commercial use.
@javax.persistence.Entity
@javax.persistence.Table(name="sip_buddies", uniqueConstraints={@javax.persistence.UniqueConstraint(columnNames={"name"})})
public class SipBuddies {
  @javax.persistence.Id
  @javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO)
  @javax.persistence.Column(name="id",length=10,nullable=false)
  private int id;

  public void setId(int id) {
    this.id = id;
  }

  public int getId() {
    return id;
  }

  @javax.persistence.Column(name="accountcode",length=20)
  private String accountcode;

  public void setAccountcode(String accountcode) {
    this.accountcode = accountcode;
  }

  public String getAccountcode() {
    return accountcode;
  }

  @javax.persistence.Column(name="allow",length=100)
  private String allow;

  public void setAllow(String allow) {
    this.allow = allow;
  }

  public String getAllow() {
    return allow;
  }

  @javax.persistence.Column(name="amaflags",length=7)
  private String amaflags;

  public void setAmaflags(String amaflags) {
    this.amaflags = amaflags;
  }

  public String getAmaflags() {
    return amaflags;
  }

  @javax.persistence.Column(name="callerid",length=80)
  private String callerid;

  public void setCallerid(String callerid) {
    this.callerid = callerid;
  }

  public String getCallerid() {
    return callerid;
  }

  @javax.persistence.Column(name="callgroup",length=10)
  private String callgroup;

  public void setCallgroup(String callgroup) {
    this.callgroup = callgroup;
  }

  public String getCallgroup() {
    return callgroup;
  }

  @javax.persistence.Column(name="cancallforward",length=3)
  private String cancallforward;

  public void setCancallforward(String cancallforward) {
    this.cancallforward = cancallforward;
  }

  public String getCancallforward() {
    return cancallforward;
  }

  @javax.persistence.Column(name="canreinvite",length=3)
  private String canreinvite;

  public void setCanreinvite(String canreinvite) {
    this.canreinvite = canreinvite;
  }

  public String getCanreinvite() {
    return canreinvite;
  }

  @javax.persistence.Column(name="context",length=80)
  private String context;

  public void setContext(String context) {
    this.context = context;
  }

  public String getContext() {
    return context;
  }

  @javax.persistence.Column(name="defaultip",length=15)
  private String defaultip;

  public void setDefaultip(String defaultip) {
    this.defaultip = defaultip;
  }

  public String getDefaultip() {
    return defaultip;
  }

  @javax.persistence.Column(name="deny",length=95)
  private String deny;

  public void setDeny(String deny) {
    this.deny = deny;
  }

  public String getDeny() {
    return deny;
  }

  @javax.persistence.Column(name="disallow",length=100)
  private String disallow;

  public void setDisallow(String disallow) {
    this.disallow = disallow;
  }

  public String getDisallow() {
    return disallow;
  }

  @javax.persistence.Column(name="dtmfmode",length=7)
  private String dtmfmode;

  public void setDtmfmode(String dtmfmode) {
    this.dtmfmode = dtmfmode;
  }

  public String getDtmfmode() {
    return dtmfmode;
  }

  @javax.persistence.Column(name="fromdomain",length=80)
  private String fromdomain;

  public void setFromdomain(String fromdomain) {
    this.fromdomain = fromdomain;
  }

  public String getFromdomain() {
    return fromdomain;
  }

  @javax.persistence.Column(name="fromuser",length=80)
  private String fromuser;

  public void setFromuser(String fromuser) {
    this.fromuser = fromuser;
  }

  public String getFromuser() {
    return fromuser;
  }

  @javax.persistence.Column(name="fullcontact",length=80)
  private String fullcontact;

  public void setFullcontact(String fullcontact) {
    this.fullcontact = fullcontact;
  }

  public String getFullcontact() {
    return fullcontact;
  }

  @javax.persistence.Column(name="host",length=31,nullable=false)
  private String host = "";

  public void setHost(String host) {
    this.host = host;
  }

  public String getHost() {
    return host;
  }

  @javax.persistence.Column(name="insecure",length=20)
  private String insecure;

  public void setInsecure(String insecure) {
    this.insecure = insecure;
  }

  public String getInsecure() {
    return insecure;
  }

  @javax.persistence.Column(name="ipaddr",length=15,nullable=false)
  private String ipaddr = "";

  public void setIpaddr(String ipaddr) {
    this.ipaddr = ipaddr;
  }

  public String getIpaddr() {
    return ipaddr;
  }

  @javax.persistence.Column(name="language",length=2)
  private String language;

  public void setLanguage(String language) {
    this.language = language;
  }

  public String getLanguage() {
    return language;
  }

  @javax.persistence.Column(name="mailbox",length=50)
  private String mailbox;

  public void setMailbox(String mailbox) {
    this.mailbox = mailbox;
  }

  public String getMailbox() {
    return mailbox;
  }

  @javax.persistence.Column(name="mask",length=95)
  private String mask;

  public void setMask(String mask) {
    this.mask = mask;
  }

  public String getMask() {
    return mask;
  }

  @javax.persistence.Column(name="md5secret",length=80)
  private String md5secret;

  public void setMd5secret(String md5secret) {
    this.md5secret = md5secret;
  }

  public String getMd5secret() {
    return md5secret;
  }

  @javax.persistence.Column(name="musiconhold",length=100)
  private String musiconhold;

  public void setMusiconhold(String musiconhold) {
    this.musiconhold = musiconhold;
  }

  public String getMusiconhold() {
    return musiconhold;
  }

  @javax.persistence.Column(name="name",length=80,nullable=false)
  private String name = "";

  public void setName(String name) {
    this.name = name;
  }

  public String getName() {
    return name;
  }

  @javax.persistence.Column(name="nat",length=5,nullable=false)
  private String nat = "";

  public void setNat(String nat) {
    this.nat = nat;
  }

  public String getNat() {
    return nat;
  }

  @javax.persistence.Column(name="permit",length=95)
  private String permit;

  public void setPermit(String permit) {
    this.permit = permit;
  }

  public String getPermit() {
    return permit;
  }

  @javax.persistence.Column(name="pickupgroup",length=10)
  private String pickupgroup;

  public void setPickupgroup(String pickupgroup) {
    this.pickupgroup = pickupgroup;
  }

  public String getPickupgroup() {
    return pickupgroup;
  }

  @javax.persistence.Column(name="port",length=5,nullable=false)
  private String port = "";

  public void setPort(String port) {
    this.port = port;
  }

  public String getPort() {
    return port;
  }

  @javax.persistence.Column(name="qualify",length=3)
  private String qualify;

  public void setQualify(String qualify) {
    this.qualify = qualify;
  }

  public String getQualify() {
    return qualify;
  }

  @javax.persistence.Column(name="regexten",length=80,nullable=false)
  private String regexten = "";

  public void setRegexten(String regexten) {
    this.regexten = regexten;
  }

  public String getRegexten() {
    return regexten;
  }

  @javax.persistence.Column(name="regseconds",length=10,nullable=false)
  private int regseconds;

  public void setRegseconds(int regseconds) {
    this.regseconds = regseconds;
  }

  public int getRegseconds() {
    return regseconds;
  }

  @javax.persistence.Column(name="restrictcid",length=1)
  private String restrictcid;

  public void setRestrictcid(String restrictcid) {
    this.restrictcid = restrictcid;
  }

  public String getRestrictcid() {
    return restrictcid;
  }

  @javax.persistence.Column(name="rtpholdtimeout",length=3)
  private String rtpholdtimeout;

  public void setRtpholdtimeout(String rtpholdtimeout) {
    this.rtpholdtimeout = rtpholdtimeout;
  }

  public String getRtpholdtimeout() {
    return rtpholdtimeout;
  }

  @javax.persistence.Column(name="rtptimeout",length=3)
  private String rtptimeout;

  public void setRtptimeout(String rtptimeout) {
    this.rtptimeout = rtptimeout;
  }

  public String getRtptimeout() {
    return rtptimeout;
  }

  @javax.persistence.Column(name="secret",length=80)
  private String secret;

  public void setSecret(String secret) {
    this.secret = secret;
  }

  public String getSecret() {
    return secret;
  }

  @javax.persistence.Column(name="type",length=6,nullable=false)
  private String type = "";

  public void setType(String type) {
    this.type = type;
  }

  public String getType() {
    return type;
  }

  @javax.persistence.Column(name="username",length=80,nullable=false)
  private String username = "";

  public void setUsername(String username) {
    this.username = username;
  }

  public String getUsername() {
    return username;
  }
// <- Generated by DB Importer
}