package br.com.jborda.asterisk;

// Generated by DB Importer ->
// DB Importer free version - not for commercial use.
@javax.persistence.Entity
@javax.persistence.Table(name="voicemessages")
public class Voicemessages {
  @javax.persistence.Id
  @javax.persistence.GeneratedValue(strategy=javax.persistence.GenerationType.AUTO)
  @javax.persistence.Column(name="id",length=10,nullable=false)
  private int id;

  public void setId(int id) {
    this.id = id;
  }

  public int getId() {
    return id;
  }

  @javax.persistence.Column(name="callerid",length=40)
  private String callerid;

  public void setCallerid(String callerid) {
    this.callerid = callerid;
  }

  public String getCallerid() {
    return callerid;
  }

  @javax.persistence.Column(name="context",length=80)
  private String context;

  public void setContext(String context) {
    this.context = context;
  }

  public String getContext() {
    return context;
  }

  @javax.persistence.Column(name="dir",length=80)
  private String dir;

  public void setDir(String dir) {
    this.dir = dir;
  }

  public String getDir() {
    return dir;
  }

  @javax.persistence.Column(name="duration",length=20)
  private String duration;

  public void setDuration(String duration) {
    this.duration = duration;
  }

  public String getDuration() {
    return duration;
  }

  @javax.persistence.Column(name="macrocontext",length=80)
  private String macrocontext;

  public void setMacrocontext(String macrocontext) {
    this.macrocontext = macrocontext;
  }

  public String getMacrocontext() {
    return macrocontext;
  }

  @javax.persistence.Column(name="mailboxcontext",length=80)
  private String mailboxcontext;

  public void setMailboxcontext(String mailboxcontext) {
    this.mailboxcontext = mailboxcontext;
  }

  public String getMailboxcontext() {
    return mailboxcontext;
  }

  @javax.persistence.Column(name="mailboxuser",length=80)
  private String mailboxuser;

  public void setMailboxuser(String mailboxuser) {
    this.mailboxuser = mailboxuser;
  }

  public String getMailboxuser() {
    return mailboxuser;
  }

  @javax.persistence.Column(name="msgnum",length=10,nullable=false)
  private int msgnum;

  public void setMsgnum(int msgnum) {
    this.msgnum = msgnum;
  }

  public int getMsgnum() {
    return msgnum;
  }

  @javax.persistence.Column(name="origtime",length=40)
  private String origtime;

  public void setOrigtime(String origtime) {
    this.origtime = origtime;
  }

  public String getOrigtime() {
    return origtime;
  }

  @javax.persistence.Column(name="recording",length=2147483647)
  private byte[] recording;

  public void setRecording(byte[] recording) {
    this.recording = recording;
  }

  public byte[] getRecording() {
    return recording;
  }
// <- Generated by DB Importer
}